language: csharp
      mono: none
      sudo: required
      dist: xenial
      dotnet: 2.2
      script:
        - cd /home/travis/build/jmacgregor-accenture/angularPlayGround/AngularExperiments/
        - dotnet restore
        - dotnet build